# Basic
title: Brian's Blog | 布莱恩部落
subtitle: A blog-orientation theme for Jekyll
# welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: With the Code, Change the World !
creator: <a href="https://brianbowu.github.io">@brianbowu</a>

url: "https://brianbowu.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 简历, description: 我的简历, url: '#'}
    - {title: 项目, description: 我参与的项目, url: '#'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: brianbowu
    github: brianbowu
    twitter: BrianBoWu
    # gplus: 107108267983477358170
    mail: wubo9935@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
